dbt_tutorial:
  outputs:
    dev:
      dbname: Adventureworks
      host: host.docker.internal 
      pass: postgres
      port: 5432
      schema: warehouse
      threads: 4
      type: postgres
      user: postgres
  target: dev
